/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "stat.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

double *
average_1(arr, size, clnt)
	int *arr;
	int size;
	CLIENT *clnt;
{
	average_1_argument arg;
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arr = arr;
	arg.size = size;
	if (clnt_call(clnt, AVERAGE, xdr_average_1_argument, &arg, xdr_double, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
minimum_1(arr, size, clnt)
	int *arr;
	int size;
	CLIENT *clnt;
{
	minimum_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arr = arr;
	arg.size = size;
	if (clnt_call(clnt, MINIMUM, xdr_minimum_1_argument, &arg, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
max_1(arr, size, clnt)
	int *arr;
	int size;
	CLIENT *clnt;
{
	max_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arr = arr;
	arg.size = size;
	if (clnt_call(clnt, MAX, xdr_max_1_argument, &arg, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

double *
stddev_1(arr, size, clnt)
	int *arr;
	int size;
	CLIENT *clnt;
{
	stddev_1_argument arg;
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arr = arr;
	arg.size = size;
	if (clnt_call(clnt, STDDEV, xdr_stddev_1_argument, &arg, xdr_double, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

double *
variance_1(arr, size, clnt)
	int *arr;
	int size;
	CLIENT *clnt;
{
	variance_1_argument arg;
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arr = arr;
	arg.size = size;
	if (clnt_call(clnt, VARIANCE, xdr_variance_1_argument, &arg, xdr_double, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
