/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "stat.h"

bool_t
xdr_data(xdrs, objp)
	XDR *xdrs;
	data *objp;
{

	if (!xdr_array(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, 200, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_average_1_argument(xdrs, objp)
	XDR *xdrs;
	average_1_argument *objp;
{
	if (!xdr_pointer(xdrs, (char **)&objp->arr, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_minimum_1_argument(xdrs, objp)
	XDR *xdrs;
	minimum_1_argument *objp;
{
	if (!xdr_pointer(xdrs, (char **)&objp->arr, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_max_1_argument(xdrs, objp)
	XDR *xdrs;
	max_1_argument *objp;
{
	if (!xdr_pointer(xdrs, (char **)&objp->arr, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_stddev_1_argument(xdrs, objp)
	XDR *xdrs;
	stddev_1_argument *objp;
{
	if (!xdr_pointer(xdrs, (char **)&objp->arr, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_variance_1_argument(xdrs, objp)
	XDR *xdrs;
	variance_1_argument *objp;
{
	if (!xdr_pointer(xdrs, (char **)&objp->arr, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return (FALSE);
	return (TRUE);
}
