/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SAMPLE_H_RPCGEN
#define _SAMPLE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXDATALEN 200

struct data {
	struct {
		u_int data_len;
		int *data_val;
	} data;
};
typedef struct data data;
#ifdef __cplusplus
extern "C" bool_t xdr_data(XDR *, data*);
#elif __STDC__
extern  bool_t xdr_data(XDR *, data*);
#else /* Old Style C */
bool_t xdr_data();
#endif /* Old Style C */


#ifdef __cplusplus
extern "C" bool_t xdr_data(XDR *, data*);
#elif __STDC__
extern  bool_t xdr_data(XDR *, data*);
#else /* Old Style C */
bool_t xdr_data();
#endif /* Old Style C */


#define SAMPLEPROG ((rpc_uint)21678)
#define SAMPLEVERS ((rpc_uint)1)

#ifdef __cplusplus
#define AVERAGE ((rpc_uint)1)
extern "C" double * average_1(data *, CLIENT *);
extern "C" double * average_1_svc(data *, struct svc_req *);
#define VARIANCE ((rpc_uint)2)
extern "C" double * variance_1(data *, CLIENT *);
extern "C" double * variance_1_svc(data *, struct svc_req *);
#define STDDEV ((rpc_uint)3)
extern "C" double * stddev_1(data *, CLIENT *);
extern "C" double * stddev_1_svc(data *, struct svc_req *);
#define MINIMUM ((rpc_uint)4)
extern "C" double * minimum_1(data *, CLIENT *);
extern "C" double * minimum_1_svc(data *, struct svc_req *);
#define MAXIMUM ((rpc_uint)5)
extern "C" double * maximum_1(data *, CLIENT *);
extern "C" double * maximum_1_svc(data *, struct svc_req *);

#elif __STDC__
#define AVERAGE ((rpc_uint)1)
extern  double * average_1(data *, CLIENT *);
extern  double * average_1_svc(data *, struct svc_req *);
#define VARIANCE ((rpc_uint)2)
extern  double * variance_1(data *, CLIENT *);
extern  double * variance_1_svc(data *, struct svc_req *);
#define STDDEV ((rpc_uint)3)
extern  double * stddev_1(data *, CLIENT *);
extern  double * stddev_1_svc(data *, struct svc_req *);
#define MINIMUM ((rpc_uint)4)
extern  double * minimum_1(data *, CLIENT *);
extern  double * minimum_1_svc(data *, struct svc_req *);
#define MAXIMUM ((rpc_uint)5)
extern  double * maximum_1(data *, CLIENT *);
extern  double * maximum_1_svc(data *, struct svc_req *);

#else /* Old Style C */
#define AVERAGE ((rpc_uint)1)
extern  double * average_1();
extern  double * average_1_svc();
#define VARIANCE ((rpc_uint)2)
extern  double * variance_1();
extern  double * variance_1_svc();
#define STDDEV ((rpc_uint)3)
extern  double * stddev_1();
extern  double * stddev_1_svc();
#define MINIMUM ((rpc_uint)4)
extern  double * minimum_1();
extern  double * minimum_1_svc();
#define MAXIMUM ((rpc_uint)5)
extern  double * maximum_1();
extern  double * maximum_1_svc();
#endif /* Old Style C */

#endif /* !_SAMPLE_H_RPCGEN */
