/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sample.h"

bool_t
xdr_data(xdrs, objp)
	XDR *xdrs;
	data *objp;
{

	if (!xdr_array(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, 200, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	return (TRUE);
}
